DL-9400 - Dependency upgrade
hmrc/company-registration-frontend pull request #346
Opened 2023-02-08 17:58 UTC by derickdamoah

!!! :guardsman: PLEASE UPDATE THE TEXT BELOW AND REMOVE THIS LINE :guardsman: !!!

# Descriptive Title - including Jira story or Github issue number

**Bug fix / New feature** (delete as appropriate)

Please include a summary / description of the change and which issue it fixes.  Include any relevant user needs and context.

## Checklist

* [ ] I've included appropriate tests with any code I've added
* [ ] I've executed the acceptance test pack locally to ensure there are no regressions
* [ ] I've added my code using logical, atomic commits, squashing as appropriate - including the Jira issue number in the commit message
* [ ] I've run a dependency check to ensure all dependencies are up to date

2023-02-13 11:38 UTC, peckover requested changes

2023-02-13 11:38 UTC, peckover commented on project/AppDependencies.scala
>      "uk.gov.hmrc"             %%  "play-ui"                         % s"9.11.0$playVersion",
This is deprecated and should be removed

2023-02-13 11:38 UTC, peckover commented on project/AppDependencies.scala
>      "uk.gov.hmrc"             %%  "govuk-template"                  % s"5.78.0$playVersion",
This is deprecated and should be removed

2023-02-17 13:49 UTC, Daveo-G approved these changes

2023-02-20 10:49 UTC, peckover approved these changes

2023-02-20 14:04 UTC, merged